apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.56.230-192.168.56.240 # <-- !!! 본인 환경에 맞게 반드시 수정 !!!
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  # 위에서 만든 IPAddressPool의 IP들을 사용하겠다고 알려줍니다.
  ipAddressPools:
  - first-pool